### ISSUE TITLE
Home Comparisons is stuck on Calculating Scores

### ISSUE THREAD

**Issue by pmichaelro** [ziebelje/beestat-issues#112]

**Comment by ziebelje** [comment]
I am not able to reproduce this on your account; is it still happening for you?

**Comment by ziebelje** [comment]
Since I was unable to reproduce this on your account I believe this issue is resolved. If not, please don't hesitate to reopen this and let me know. Thanks!

**Comment by mihaicristianpetrescu** [comment]
Home comparisons seems to be working now.
