### ISSUE TITLE
Support for other thermostats / custom data uploads

### ISSUE THREAD

**Issue by ziebelje** [ziebelje/beestat-issues#19]
``I've been wanting something like this since I bought my Zwave thermostat many, many years ago. Speaking of which, could you possibly add support for generic thermostats like mine? Alternatively, would it be possible to pull information from thermostats and temperature sensors from Home Assistant?``

https://old.reddit.com/r/homeautomation/comments/8hw83h/analyze_your_hvac_usage_and_home_efficiency_with/dyn6xdw/

**Comment by jamesnw** [comment]
I would also appreciate support for Honeywell thermometers. I have some experience working with Honeywell data (although mostly through scrapping in an unsustainable way) that may be useful.

**Comment by ziebelje** [comment]
See #14. My only immediate plans are to add Nest support. Depending on how that goes I may consider other thermostats.
