### ISSUE TITLE
Add some way to subscribe to updates

### ISSUE THREAD

**Issue by ziebelje** [ziebelje/beestat-issues#21]
> Is there somewhere we can signup for updates? Essentially I'd just like to know when Nest functionality is available!

https://old.reddit.com/r/homeautomation/comments/8hw83h/analyze_your_hvac_usage_and_home_efficiency_with/dynbm2i/

**Comment by huangcuilyn** [comment]
Subscribing to the thread to find out when I can subscribe to updates...

**Comment by ziebelje** [comment]
I will be sending subscription confirmations to all currently signed up users shortly. Just click confirm in that email if you want to get updates!

Alternatively, you can sign up here: http://eepurl.com/dum59r
