### ISSUE TITLE
Any plans to support humidifiers?

### ISSUE THREAD

**Issue by hmspain** [ziebelje/beestat-issues#25]
I love what I see so far; Ecobee should buy your code!  Support for AUX is built into Ecobee, and I would love to see this kind of detail on my humidifier.

Thank you!

**Comment by ziebelje** [comment]
Yeah, this should be possible. Ecobee returns humidifier/dehumidifier data from their API. I'll look into adding it!

**Comment by hmspain** [comment]
Thank you!  I notice you reference "Aux", but I think this is heat in your display.

**Comment by ziebelje** [comment]
Yeah, see #6. The ecobee API is telling me that the aux is on but their website and data download says otherwise. I have a ticket open with ecobee about it but they have not yet gotten back with me.

**Comment by ziebelje** [comment]
Indoor humidity and humidifiers are now supported on the Recent Activity graph in beestat 1.2 (coming soon). I have plans (#60) to enable custom graphs focused on just certain things in the future, but this issue is satisfied.
