### ISSUE TITLE
Database query fails when time zone is positive UTC

### ISSUE THREAD

**Issue by Vertikar** [ziebelje/beestat-issues#28]
Have connected account successfully, but don't get past the updating your thermostats page.
Can't see any connection timeouts in Chrome Inspector or any errors.

**Comment by Vertikar** [comment]
Looking at firefox, have seen some errors in the console.
Appears to be in hitting the API call failed here:
````
beestat.prototype.api_ = function (a, e, c, d) {
  var b = new XMLHttpRequest;
  b.addEventListener('load', function () {
    var a = JSON.parse(this.responseText);
    if (!0 !== a.success) if (1004 === a.data.error_code) localStorage.clear(),
    window.location.href = '/';
     else throw Error('API call failed.');
    void 0 !== d && d(a.data)
  });
  'api' === a && 'batch' === e ? b.open('POST', '../api/?batch=' + JSON.stringify(c) + '&api_key=<removed>')  : b.open('POST', '../api/?resource=' + a + '&method=' + e + '&arguments=' + JSON.stringify(c) + '&api_key=<removed>');
  b.send()
};

````

Here's the error from the console after prettyfying the code:

> Error: API call failed.
> dashboard.js:14719
> beestat.prototype.api_/<
> dashboard.js:14719
> r.prototype.wrap/t._rollbar_wrapped
> rollbar.min.js:formatted:237
>

**Comment by Vertikar** [comment]
I suspect it's due to some responses that are returning null in the data, or another one that returned a DB error.
Will add more details later.

**Comment by ziebelje** [comment]
Thanks for the issue report! This should now be fixed.

**Comment by Vertikar** [comment]
Looks good, thanks for getting onto this so quickly!
