### ISSUE TITLE
Ecobee authorization incorrectly says beestat can modify data

### ISSUE THREAD

**Issue by ziebelje** [ziebelje/beestat-issues#33]
![image](https://user-images.githubusercontent.com/3288812/41679179-5d287c36-749b-11e8-80d5-4f8733f90c03.png)

**Comment by ziebelje** [comment]
Need to submit ticket to ecobee to investigate.

**Comment by ziebelje** [comment]
Ticket submitted

**Comment by ziebelje** [comment]
I ping ecobee every week asking for an update this but have not received any comment yet.

**Comment by rct** [comment]
Just signed up today.  This issue seems to be resolved.  Sorry I didn't capture the text when authorizing beestat but it seemed to indicate I was only granting read access.   Thanks.

**Comment by ziebelje** [comment]
And so it is. Thanks for letting me know!

![image](https://user-images.githubusercontent.com/3288812/50987820-b396b280-14d8-11e9-8cae-871fee82bf4c.png)
