### ISSUE TITLE
Fix runtime overreporting

### ISSUE THREAD

**Issue by ziebelje** [ziebelje/beestat-issues#36]
Ex: This implies that the AC ran for more than 24 hours on some days.

Thanks, @BigDogJonx for your comments on this. Moving this specific discussion here.

![chart](https://user-images.githubusercontent.com/3288812/42685951-72114c94-8662-11e8-88df-84cbfb83d76e.png)

**Comment by ziebelje** [comment]
@BigDogJonx, to answer your question from the other issue:

1. Yes, I flipped the order of the text labels to show Cool 1 on top of Cool 2, but now that you mention it I may change it to match the graph. Not sure. Preference?
2. Yeah, here's my runtime from Home IQ for that day. Clearly something is a bit wrong on my graph. :)
![image](https://user-images.githubusercontent.com/3288812/42686794-0386970e-8665-11e8-8e1b-0c339c9f7e5b.png)


> Nice. On your example, your popup though still shows a total of 29hrs and seems like Cool1/2 flipped around in that popup. Just pointing that out, but like you said you still working on it.
> 
> But out of curiosity, on this setup what is your run times? Like do you really have 13-16hrs of Cool1 or 2 stage?

**Comment by ziebelje** [comment]
Properly fixed for the next release. I am now setting the graph max to a static value (24 hours in the case of group by day) so you aren't deceived by a shifting axis. Additionally the graph no longer overreports runtime by summing stage1 and stage2.

Screenshot:
![image](https://user-images.githubusercontent.com/3288812/42687852-29e4a212-8668-11e8-9792-91db98a63401.png)

**Comment by BigDogJonx** [comment]
@ziebelje Looks good.  Yea I would look into why your unit is running nonstop for almost 16hrs.  Seems excessive, maybe your HVAC unit isnt working right.

**Comment by ziebelje** [comment]
Yeah, it got to be 90 out that day but the heat pump (just a couple years old) wasn't keeping up for some reason. I'll look into it.

**Comment by BigDogJonx** [comment]
Yea I would definitely get it checked out, Im in ATL and it was 90+ and my new unit that was installed just last year only ran for about 9hrs on that day.

**Comment by ziebelje** [comment]
Kind of related: this is exactly why I have been working on temperature profiles like this:

![ziebee - temperature profile 1](https://user-images.githubusercontent.com/3288812/42705869-bfe03666-86a2-11e8-9bd8-a0b4105c2806.png)

After this next release one of the things I want to do is build some actual useful comparisons to the temperature profile section. If we were to compare our two graphs I would probably see that my home gains heat at a faster rate than yours when it's 90 out (my graph says +0.4°F/hour at 90°F out). The end goal here is basically to say "You're in the top 90% of homes" or whatever. This particular metric looks at heat gain/loss data when your heat or air is not running.

**Comment by BigDogJonx** [comment]
Nice now I understand what this Temperature Profile is, I kept trying to understand what this chart shows me.  Mines about 0.3F at 90F outside.

![image](https://user-images.githubusercontent.com/29067981/42707161-49136558-86a7-11e8-8be0-ff6f56142cc0.png)

I definitely use these smart thermostats be it Ecobee or other brands (manage other buildings too) to also let me know there is a problem with a unit when its running way too long like say your example, usually ends up being that something like compressor outside not running (like a bad capacitor or contactor) or outside fan isnt running, or inside unit fan isnt running or blower motor, basically helps me understand there is a problem before someone complains that hey this area is way too hot or too cold.
