### ISSUE TITLE
Celsius Temp Rounding

### ISSUE THREAD

**Issue by pbros** [ziebelje/beestat-issues#64]
Hello,

In the latest release I noticed that Celsius temperatures are not being rounded nicely. They should be rounded to 1 or 2 decimal points.

Ex:

![image](https://user-images.githubusercontent.com/17840445/48007046-c958b780-e0e4-11e8-9c34-b96dcbcf277d.png)

**Comment by ziebelje** [comment]
Refactored the internal temperature conversion functionality to be a bit more robust and easier to use. This issue is fixed and will go live with beestat 1.2 sometime this week.

![image](https://user-images.githubusercontent.com/3288812/48068663-6f69f780-e1a1-11e8-98a8-56343c79dc85.png)
