### ISSUE TITLE
Unable to reset aggregation time

### ISSUE THREAD

**Issue by trs-80** [ziebelje/beestat-issues#79]
Selected 1 year for the aggregation but the UI is unable to load the data and hangs on:
"Loading Aggregate Runtime"

There is no way to reset the aggregation back to a working time range, even when loading in a different browser it would appear something on the server side has saved a value of what aggregation was previously requested for my ecobee account.

![image](https://user-images.githubusercontent.com/109326/49466445-160bdd00-f7ce-11e8-9e70-9444e856a3e3.png)

**Comment by ziebelje** [comment]
Could you post your thermostat serial number or send it to contact@beestat.io? I'll take a look.

But yes, those settings are stored server-side so when you reload across devices it retains your preferences.

**Comment by ziebelje** [comment]
I just connected to your account and was unable to duplicate the issue. I also don't have any errors logged for your account. I changed the setting for you back to two months...if you try to connect now does it work if you change the time range?

**Comment by trs-80** [comment]
The aggregated data is displaying correctly now. Thank you.

Not sure if it is related, but also having trouble with the "Generating Efficiency Profile" panel and originally thought it had something to do with the fact that it was a new feature.

**Comment by ziebelje** [comment]
Currently having trouble or had trouble earlier? I just double checked and that graph is loading fine for me on your account.
I'm not really sure what happened at this point. Based on how things work I have a few suspicions but I'll have to sit down later this evening and look more carefully through the logs to figure it out.

**Comment by ziebelje** [comment]
Now that I have error logging properly turned on I'm seeing this more. It's strictly on Mobile Safari (12).

Error is:
> TypeError: undefined is not an object (evaluating 'Object.keys(beestat.cache.user)')

After this error is triggered it seems to break stuff. Not sure why yet, but looking!

**Comment by ziebelje** [comment]
Ugh I hate time zones. The Aggregate Runtime and Home Efficiency graphs both sit there on the dashboard and spin until they see that the thermostat has fully synced all of the data that they need. This logic is based on a couple of dates stored in the database. It just so happens that the dates get misaligned by a few hours due to time zones and both of those graphs then think that they don't have all of the data.
I can fix this and correct all the data but I'm tired so I'll do it later so I don't screw it up. I also don't think the error I posted above is directly related to this problem; it just happened to happen at the same time this issue appeared.

**Comment by ziebelje** [comment]
Never mind; this isn't time zones. This is a bug with the initial sync. When you first connect to beestat it starts syncing your data one week at a time starting from now and moving backwards. There is an edge case that affects only new users and only sometimes...basically depending on what day it is and what day your thermostat was first connected. Anyone I manually fix this for won't encounter the problem in the future. Will correct. Appreciate your patience on this!

**Comment by trs-80** [comment]
The timezone could be a component of this.  When I had the problem I was traveling and not in the timezone I was when I first used beestat.io

**Comment by ziebelje** [comment]
It wasn't. :) I confirmed everything and duplicated the issue this morning. Fixed and notified all affected users.

Thanks for reporting!
