### ISSUE TITLE
Missing Outdoor Temperature 

### ISSUE THREAD

**Issue by dannysporea** [ziebelje/beestat-issues#83]
The graphs are missing outdoor temperature prior to April 2018... I was trying to compare runtime based on outdoor temperature with previous year, but older outdoor temperatures are missing.

**Comment by ziebelje** [comment]
Ecobee purged weather data prior to April 2018 as a result of switching weather providers. If you joined beestat after this happened you will not have access to this historical data.

Kind of a bummer. I'd love to connect to a weather provider to be able to get this historical data but it's simply not a priority right now. I'll keep this open as a reminder to look into doing that in the future.

**Comment by dannysporea** [comment]
Any way of loading data from the Ecobee export spreadsheets? I have everything downloaded from the beginning of time...

**Comment by ziebelje** [comment]
It would be easiest to have one combined file per thermostat.

**Comment by dannysporea** [comment]
Emailed. Thank you!
