### ISSUE TITLE
Complement "Home Efficiency" loss/gain feature with heating/cooling gain/loss

### ISSUE THREAD

**Issue by MiniMook** [ziebelje/beestat-issues#85]
This is a useful-sounding feature request to my ear:

The "Home Efficiency" section of beestat, the one that tells me internal temperature changed based on outdoor temperature, tells me how well my house is insulated, effectively.

Can we get a similar section on home heating and cooling efficiency, for those of us with heat pump-based systems? The calculation is similar, just use "HVAC fully on time" rather than "HVAC fully off time." You can additionally split it based on staging and auxiliary heat. For each stage, the zero point of the regression is the balance point of the system.

Given what's already implemented this seems low-cost to me, though I don't know fully what's planned on Patreon. Maybe it already exists.

**Comment by ziebelje** [comment]
This is actually already planned for 1.3. :)

There's a more detailed writeup and screenshot here:
https://www.patreon.com/posts/home-efficiency-23114758

If you're not a Patron, the gist of it is more or less what you described above, but for cooling as well, and for all systems, not just heat pumps. I think it's going to be pretty cool.

I'll keep this open but I dropped it in the 1.3 milestone. I'll complete this when that's done, but you'll also get an email if you're subscribed to the [mailing list](http://eepurl.com/dum59r).

**Comment by MiniMook** [comment]
Aha, very cool. If you keep this going I may decide to make a Patreon account finally :)

**Comment by ziebelje** [comment]
How's this? ;)

Splitting up by stages is not a planned feature for 1.3. After this goes live and I have a chance to review feedback I may consider it. Otherwise these changes will likely go live towards the end of this month.

![2019-03-04_11-19-32](https://user-images.githubusercontent.com/3288812/53830945-910d9c80-3f51-11e9-8c56-7ced930f7a3c.gif)

**Comment by MiniMook** [comment]
It looks great, I'm looking forward to seeing it

**Comment by ziebelje** [comment]
Likely going live tomorrow evening and being officially announced next week.
