### ISSUE TITLE
Double counting Stage 2 runtime

### ISSUE THREAD

**Issue by sup-one** [ziebelje/beestat-issues#89]
I just got a new 2 stage furnace and noticed a calculation error in the Recent Activity and Aggregate Runtime.

While Stage 2 is running, the time is being counted against Stage 1 and Stage 2 totals.  This is especially visible in the Aggregate Runtime when I compare it to the old run times prior to the install of the new furnace (old one was only 1 stage).

For example on Jan 7 (my largest runtime on old furnace) the bar graph represents 9.5 hours.  On Jan 17 my total run time was 10.5 hours but the bar graph is much taller than the old 9.5 hour graph.  The reason is that Stage 1 runtime includes both Stage 1 and Stage 2 and then you add Stage 2 again on top and come up with 12.5 hour bar graph.

**Comment by ziebelje** [comment]
If you send your thermostat serial to contact@beestat.io I can take a look. I feel like you already sent it to me once but I couldn't find it. But just from my graphs, here are a couple examples:

![image](https://user-images.githubusercontent.com/3288812/51448182-ad7fad80-1cf2-11e9-930f-4f5231706d64.png)
This incorrectly shows the heat stage 1 runtime. I agree with you here and will correct this. In reality:
Heat 1 ran for 1h 30m
Heat 2 kicked in and ran for 3h 31m
In total, the "heat" (regardless of stage) was on for 5h 1m.

![image](https://user-images.githubusercontent.com/3288812/51448258-41517980-1cf3-11e9-8d79-87a7ce542069.png)
This correctly shows all runtimes. Without seeing your data I can't be 100% sure there's not a bug, but I believe it's correct.
Heat 1 ran for 6h 0m
Heat 2 ran for 11h 36m
In total, the "heat" (regardless of stage) was on for 17h 36m. The bar is the sum of those two numbers and reflects the total "heat" runtime for that period.

**Comment by ziebelje** [comment]
This is fixed and will go live later today. Appreciate the help on this one!
