### ISSUE TITLE
Auto-refresh site after certain interval

### ISSUE THREAD

**Issue by vincep5** [ziebelje/beestat-issues#98]
I'd like to see the site auto refresh the data in an interval.  Sometimes, I have the tab open and the data after 5 minutes is stale and I have to manually F5 the page to get the data refreshed.

**Comment by ziebelje** [comment]
Yeah...it actually does this but I've been having some problems with the automatic sync so the only way to actually get updated data is to refresh the page which forces a sync for your single user.
I've been trying to diagnose and fix for the past couple of days...the process that does the syncing is hanging for some reason and I have to manually kill it.
I'll close this issue out when I figure out what's going on.

**Comment by ziebelje** [comment]
I believe I've tracked this down. I have a scheduled job that runs once per minute that looks at all users and determines, based on their recent activity, whether or not to sync their data. This job is getting stuck by what looks to be a hung connection to ecobee. I have a timeout on making the initial connection, but no timeout once the connection is established. The ecobee servers are never responding to my request, so the sync just sits there and holds everything up.

I think this is also the underlying issue with the missing data. Thermostats are making connections to the ecobee servers to report data that are then getting hung up so no additional data can be reported until that connection is closed.

**Comment by ziebelje** [comment]
To fix I'll probably add a connection timeout and call it a day. This also killed my database server because I didn't notice the hung connections. After restarting the sync too many times all the hung connections sucked up enough memory that MySQL ran out of memory, crashed, and then couldn't even restart.

**Comment by vincep5** [comment]
I think you should work for Ecobee and help fix their current woes

**Comment by ziebelje** [comment]
This has been working for a bit and is stable again.

**Comment by vincep5** [comment]
Site does not refresh even after 10-15mins.

**Comment by ziebelje** [comment]
This should start working again...the background syncing was broken. Thanks for the note!
